# Generated by Django 5.2.17 on 2026-09-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wave', 'Wave maintenant'), ('cash_on_delivery', 'Paiement à la livraison')], default='wave', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'À vérifier'), ('due_on_delivery', 'À régler à la livraison'), ('confirmed', 'Paiement confirmé')], default='pending', max_length=16),
        ),
    ]
