# Generated by Django 5.2.17 on 2026-09-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='request_type',
            field=models.CharField(choices=[('return', 'Retour / remboursement'), ('exchange', 'Échange')], default='return', max_length=8),
        ),
    ]
