# Generated by Django 5.2.17 on 2026-09-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_product_size_guide_returnrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_points_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
